default_pulling_interval: 10
token: "RCHB9uNJzZPyklX4jJ0da0DmnaPaVB284jPMfPmR"
platform_host_url: http://localhost:8080
plugins:
  - type: druid
    name: druid_prod
    host: http://druid-prod-1-group-router.data-processing.adswizz.com
    port: 8080