default_pulling_interval: 10
token: "T96HG4NTha6bLenXt6OLwlVoRu00Gd63QobNs4C7"
platform_host_url: http://localhost:8080
plugins:
  - type: druid
    name: imply-query-prod
    host: http://imply-query-prod-01.data-processing.adswizz.com
    port: 8888