default_pulling_interval: 1
token: "eXpQjVBWPqamCyzOxHL6gjEJ4SgrOGlEGzgPcvRI"
platform_host_url: http://localhost:8080
plugins:
  - type: druid
    name: druid_collector
    host: "http://imply-query-devel.extc.adswizz.com"
    port: 8888